catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
)
urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path("redactors<int:pk>/update/", RedactorUpdateView.as_view(), name="redactor-update"),
    path("redactors/<int:pk>/delete/", RedactorDeleteView.as_view(), name="redactor-delete"),
]


app_name = "catalog"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
]

catalog/models.py
from datetime import date

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.functions import datetime
from django.urls import reverse
from django.utils import timezone


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(default=datetime.datetime.today)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="newspapers")

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return f"{self.title} (topic: {self.topic.name}, published date: {self.published_date})"

    def get_absolute_url(self):
        return reverse("catalog:newspaper-detail", args=[str(self.id)])


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("catalog:redactor-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from catalog.models import Newspaper, Redactor


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", )


class NewspaperForm(forms.ModelForm):
    redactors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by title"
            }
        )
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from catalog.forms import RedactorCreationForm, NewspaperForm, NewspaperSearchForm, TopicSearchForm, RedactorSearchForm
from catalog.models import Newspaper, Redactor, Topic


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_newspapers = Newspaper.objects.count()
    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_newspapers": num_newspapers,
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "catalog/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "catalog/topic_list.html"
    context_object_name = "topic_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form.html"


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_form.html"


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("catalog:topic-list")
    template_name = "catalog/topic_confirm_delete.html"


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")
        form = NewspaperSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    success_url = reverse_lazy("catalog:newspaper-list")
    form_class = NewspaperForm


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    success_url = reverse_lazy("catalog:newspaper-list")
    form_class = NewspaperForm


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("catalog:newspaper-list")
    template_name = "catalog/newspaper_confirm_delete.html"


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Redactor.objects.prefetch_related("newspapers")
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    success_url = reverse_lazy("catalog:redactor-list")
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    fields = "__all__"
    success_url = reverse_lazy("catalog:redactor-list")
    template_name = "catalog/redactor_form.html"


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("catalog:redactor-list")
    template_name = "catalog/redactor_confirm_delete.html"

templates/catalog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Home page</title>
{% endblock %}

{% block content %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
  <h1>Newspaper Agency Home</h1>
  <p>Welcome to the Leading Newspaper Agency!</p>
  <h3>Newspaper Agency's datalist: </h3>
    <ul>
      <li>Num newspapers: {{ num_newspapers }}</li>
      <li>Num redactors: {{ num_redactors }}</li>
      <li>Num topics: {{ num_topics }}</li>
    </ul>
    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}

templates/catalog/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Newspaper</h1>

  <p>Are you sure you want to delete the newspaper: {{ newspaper }}?</p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />

  </form>

{% endblock %}

templates/catalog/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ newspaper.title }}
    <a href="{% url 'catalog:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'catalog:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <hr>
  <table class="table">
      <tr>
        <th>ID</th>
        <th>Redactor</th>
        <th>Content</th>
        <th>Published date</th>
      </tr>
      {% for publisher in newspaper.publishers.all %}
        <tr>
          <td>
            {{ publisher.id }}
          </td>
          <td>
            {{ publisher.username }}
          </td>
          <td>
            {{ newspaper.content }}
          </td>
          <td>
            {{ newspaper.published_date }}
          </td>
        </tr>
      {% endfor %}
    </table>
{% endblock %}

templates/catalog/newspaper_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} Newspaper</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">

  </form>

{% endblock %}

templates/catalog/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Newspaper list
    <a href="{% url 'catalog:newspaper-create' %}" class="btn btn-primary link-to-page" style="float: right">
      Create
    </a>
  </h1>
  {% if search_form %}
    {% include "includes/search_form.html" %}
  {% endif %}
  <br>
  {% if newspaper_list %}
    <ul>
    {% for newspaper in newspaper_list %}
      <li>
        <a href="{{ newspaper.get_absolute_url }}">{{ newspaper.id }}</a>
        {{ newspaper.title }} ({{ newspaper.topic }})
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Redactor</h1>

  <p>Are you sure you want to delete the redactor: {{ redactor }}?</p>
  <p><i>All newspapers with this redactor will be also deleted!</i></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />

  </form>

{% endblock %}

templates/catalog/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ redactor.first_name }} {{redactor.last_name}}
    <a href="{% url 'catalog:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'catalog:redactor-update' pk=redactor.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p><strong>Username: </strong>{{ redactor.username }}</p>
  <p><strong>Is staff: </strong>{{ redactor.is_staff}}</p>
  <p><strong>Years of experience: </strong>{{ redactor.years_of_experience }}</p>
  <div class="ml-3">
    <h3>Newspapers: </h3>
    {% for newspaper in redactor.newspapers.all %}
      <hr>
      <p class="text-muted">id: {{ newspaper.id }}</p>
      <p>Title: {{ newspaper.title }}</p>
      <p>Topic: {{ newspaper.topic }}</p>
    {% empty %}
    <p>No newspapers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/redactor_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}

  <h1>Create Redactor
    <a class="btn btn-primary" style="float: right" href="{% url 'catalog:redactor-create' %}">Create</a>
  </h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>

{% endblock %}

templates/catalog/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Redactor list
    <a href="{% url 'catalog:redactor-create' %}" class="btn btn-primary link-to-page" style="float: right">
      Create
    </a>
  </h1>
  {% if search_form %}
    {% include "includes/search_form.html" %}
  {% endif %}
  <br>
  {% if redactor_list %}
    <ul>
      {% for redactor in redactor_list %}
        <li><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }}</a> ({{ redactor.first_name }} {{ redactor.last_name }})</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Topic</h1>

  <p>Are you sure you want to delete the topic: {{ topic }}?</p>
  <p><i>All newspapers with this topic will be also deleted!</i></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />

  </form>

{% endblock %}

templates/catalog/topic_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} Topic</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>

{% endblock %}

templates/catalog/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Topic List<a class="btn btn-primary" style="float: right" href="{% url 'catalog:topic-create' %}">Create</a></h1>
  {% if search_form %}
    {% include "includes/search_form.html" %}
  {% endif %}
  <br>
  {% if topic_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for topic in topic_list %}
        <tr>
          <td>
            {{ topic.id }}
          </td>
          <td>
            {{ topic.name }}
          </td>
          <td>
            <a style="color: blue" href="{% url 'catalog:topic-update' pk=topic.id %}">UPDATE</a>
          </td>
          <td>
            <a style="color: red" href="{% url 'catalog:topic-delete' pk=topic.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no Topics in Newspaper Agency</p>
  {% endif %}
{% endblock %}